apiVersion: apps/v1
kind: Deployment
metadata:
  name: basketball-notifications-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: basketball-notifications
  template:
    metadata:
      labels:
        app: basketball-notifications
    spec:
      containers:
        - image: lgaljo/rt_basketball_notifications:latest
          name: basketball-notifications
          env:
            - name: KUMULUZEE_CONFIG_ETCD_HOSTS
              value: http://etcd:2379
            - name: KUMULUZEE_DISCOVERY_ETCD_HOSTS
              value: http://etcd:2379
            - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
              value: jdbc:postgresql://ella.db.elephantsql.com/kzkuvmbs
            - name: KUMULUZEE_DATASOURCES0_USERNAME
              value: kzkuvmbs
            - name: KUMULUZEE_DATASOURCES0_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pg-pass-notifications
                  key: KUMULUZEE_DATASOURCES0_PASSWORD
            - name: RESTCONFIG_D7TOKEN
              valueFrom:
                secretKeyRef:
                  name: d7-token
                  key: RESTCONFIG_D7TOKEN
            - name: RESTCONFIG_D7USERNAME
              valueFrom:
                secretKeyRef:
                  name: d7-username
                  key: RESTCONFIG_D7USERNAME
            - name: RESTCONFIG_D7PASSWORD
              valueFrom:
                secretKeyRef:
                  name: d7-password
                  key: RESTCONFIG_D7PASSWORD
          ports:
            - containerPort: 8083
              name: server
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health/live
              port: server
            initialDelaySeconds: 20
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /health/ready
              port: server
            initialDelaySeconds: 20
            periodSeconds: 3
---

apiVersion: v1
kind: Service
metadata:
  name: basketball-notifications
spec:
  type: ClusterIP
  ports:
    - port: 8083
      protocol: TCP
      targetPort: server
  selector:
    app: basketball-notifications