kumuluzee:
  name: basketball-notifications
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8083
    http:
      port: 8083
  datasources:
    - jndi-name: jdbc/notificationsDS
      connection-url: jdbc:postgresql://ella.db.elephantsql.com/kzkuvmbs
      username: kzkuvmbs
      password: XRaxJulUpB-cwAZAopySsQAJQ9wfs01n
      pool:
        max-size: 1
  health:
    checks:
      data-source-health-check:
        type: liveness
        jndi-name: jdbc/notificationsDS
      disk-space-health-check:
        threshold: 100000000

  metrics:
    web-instrumentation:
      - name: notifications-endpoint
        url-pattern: /v1/notifications/*
  logs:
    config-file: '<?xml version="1.0" encoding="UTF-8"?>
                          <Configuration name="comments">
                              <Appenders>
                                  <Console name="console" target="SYSTEM_OUT">
                                      <PatternLayout pattern="%d %p %marker %m %X %ex %n"/>
                                  </Console>
                                  <Socket name="logstash" host="906c451a-bc58-4cb6-8145-6a2d768e120b-ls.logit.io"
                                  port="26828" protocol="UDP">
                                      <JSONLayout complete="false" compact="true" eventEol="true" charset="UTF-8" properties="true"/>
                                  </Socket>
                              </Appenders>
                              <Loggers>
                                  <!-- Default logger -->
                                  <Root level="all">
                                      <AppenderRef ref="console" level="info" />
                                      <AppenderRef ref="logstash" level="info" />
                                  </Root>
                              </Loggers>
                          </Configuration>'
  rest-client:
    registrations:
      - class: api
        url: http://localhost:8083/v1
        read-timeout: 5000
  cors-filter:
    servlet:
      allow-origin: "*"
      supported-methods: "GET,POST,HEAD,OPTIONS,PUT,DELETE"
  discovery:
    cluster: 1
    etcd:
      hosts: http://localhost:2379
    ttl: 30
    ping-interval: 5
  config:
    start-retry-delay-ms: 500
    max-retry-delay-ms: 900000
    etcd:
      hosts: http://localhost:2379

rest-config:
  maintenance-mode: false
  api-token: htn12kss3
  d7-token: ZXpvcjU2MzA6QlluYzZkY1I=
  d7-username: ezor5630
  d7-password: BYnc6dcR
